import type { Metadata } from "next";
import { Salt } from "./providers/Salt";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Salt>{children}</Salt>
      </body>
    </html>
  );
}
